<!DOCTYPE html>
<html>
    <head>
        <script src="js/gameScores.js" defer></script>
        <script src="js/displayGames.js" defer></script>
        <script src="js/addNewGame.js" defer></script>
        <script src="js/addNewUser.js" defer></script>
        <meta charset="utf-8"/>
        <title>Gaming Leaderboard</title>
        <link href="css/styles.css" type="text/css" rel="stylesheet">
    </head>
    <body>
    <section id="modal">

    </section>

        <h1>Gaming Leaderboard</h1>
        <h2>Games:</h2>
        <div>
            <label>Add a new game:</label>
            <input id="addGame" type="text" />
            <input id="submitGame" type="submit">
        </div>
        <section id="games">

        </section>

        <h2>Users:</h2>
        <div>
            <label>Add a new user:</label>
            <input id="addUser" type="text" />
            <input id="submitUser" type="submit">
        </div>
        <section id="users">

        </section>
    </body>
</html>
